# Generated by Django 4.0.6 on 2022-08-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schreg', '0002_alter_schoolprofile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school_proprietor',
            new_name='school_Proprietor',
        ),
    ]
