# Generated by Django 4.0.6 on 2022-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schreg', '0003_rename_school_proprietor_schoolprofile_school_proprietor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_Type',
            field=models.CharField(help_text='Private or Public', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_Proprietor',
            field=models.CharField(help_text='If Public fill in Federal owned or State owned', max_length=50),
        ),
    ]
