# Generated by Django 4.0.6 on 2022-08-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schreg', '0004_schoolprofile_school_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('school_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='schreg.schoolprofile')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='file_field',
            field=models.FileField(help_text='Upload the "Certificate of Registration" of the School here.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_Proprietor',
            field=models.CharField(help_text="If 'Public', fill in 'Federal owned' or 'State owned'. ", max_length=50),
        ),
    ]
