# Generated by Django 4.0.6 on 2022-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schreg', '0005_staffinfo_alter_schoolprofile_file_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='type',
            new_name='school_Category',
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='staff_role',
            field=models.CharField(choices=[('PROPRIETOR', 'Proprietor'), ('PRINICIPAL', 'Principal'), ('BURSAR', 'Bursar'), ('ADMIN', 'Admin')], default='Proprietor', max_length=10),
        ),
    ]
