# Generated by Django 4.1 on 2022-08-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schreg', '0006_rename_type_schoolprofile_school_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='staff_role',
            field=models.CharField(choices=[('PROPRIETOR', 'Proprietor'), ('PRINICIPAL', 'Principal'), ('BURSAR', 'Bursar')], default='Proprietor', max_length=10),
        ),
    ]
