# Generated by Django 4.0.6 on 2022-08-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name of schools')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'client'), (2, 'parent'), (3, 'student')], default=1, help_text='specificy whether your a school owner, parent or tudent'),
        ),
        migrations.AddField(
            model_name='client',
            name='School_name',
            field=models.ForeignKey(max_length=400, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.schools'),
        ),
    ]
