# Generated by Django 4.1 on 2022-08-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='bursar_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='bursar_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='principal_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='principal_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='proprietor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='proprietor_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
