# Generated by Django 4.1 on 2022-08-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=50)),
                ('name_of_parent', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
                ('school_owed', models.CharField(max_length=250)),
                ('amount_owed', models.IntegerField()),
                ('status', models.CharField(choices=[('Abandoned payment', 'Abandoned payment'), ('Pending payment', 'Pending payment'), ('Completed', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
